#!/system/bin/sh
# CueBoxx Boot Script — {{DEVICE_NAME}}
# Generated by CueBoxx Android Setup
# Location: /data/adb/service.d/cueboxx-boot.sh
# Runs automatically on boot via Magisk

# Wait for Android to fully boot
while [ "$(getprop sys.boot_completed)" != "1" ]; do sleep 2; done
sleep 10

# Enable ADB over WiFi
setprop service.adb.tcp.port {{ADB_PORT}}
stop adbd
start adbd

# Launch VolksPC
am start -n {{VOLKSPC_ACTIVITY}}
sleep 5

# Start HDMI watcher in background (if display output is available)
if [ "{{HDMI_ENABLED}}" = "true" ]; then
    sh /data/local/tmp/hdmi-watcher.sh &
fi
