#!/system/bin/sh
# CueBoxx HDMI Watcher — {{DEVICE_NAME}}
# Generated by CueBoxx Android Setup
# Location: /data/local/tmp/hdmi-watcher.sh
# Polls for external display and launches CuePlayer in Chrome fullscreen

LAUNCHED=0

while true; do
    if dumpsys display 2>/dev/null | grep -q "type EXTERNAL" 2>/dev/null; then
        if [ "$LAUNCHED" -eq 0 ]; then
            sleep 5

            # Find the highest displayId (external is always the newest)
            DISPLAY_ID=$(dumpsys display 2>/dev/null \
                | grep "displayId [0-9]" 2>/dev/null \
                | grep -o "displayId [0-9]*" \
                | grep -o "[0-9]*" \
                | sort -n | tail -1)

            if [ -n "$DISPLAY_ID" ] && [ "$DISPLAY_ID" -gt 1 ]; then
                # Kill existing Chrome and relaunch on external display
                am force-stop com.android.chrome
                sleep 2
                am start \
                    --display "$DISPLAY_ID" \
                    --activity-clear-task \
                    -n com.android.chrome/com.google.android.apps.chrome.Main \
                    -a android.intent.action.VIEW \
                    -d "{{CUEPLAYER_URL}}" \
                    > /dev/null 2>&1
                sleep 5

                # Try to fullscreen Chrome (tap coordinates are approximate)
                # These may need adjusting for your display resolution
                input -d "$DISPLAY_ID" tap 300 130   # Open window dropdown
                sleep 1
                input -d "$DISPLAY_ID" tap 300 170   # Tap fullscreen
                sleep 2
                input -d "$DISPLAY_ID" tap 960 540   # Tap page to trigger browser fullscreen

                LAUNCHED=1
            fi
        fi
    else
        LAUNCHED=0
    fi

    sleep 3
done
